// Generated by CoffeeScript 1.7.1
(function() {
  var args, asciimo, colors, copypaste, feeling, fetchGif, http, key, next, readline, url;

  readline = require('readline');

  http = require('http');

  asciimo = require('./node_modules/asciimo/lib/asciimo').Figlet;

  colors = require('./node_modules/asciimo/lib/colors');

  copypaste = require('copy-paste');

  key = "rX7kbMzkGu7WJwvG";

  url = "http://api.gifme.io/v1/gifs/random?key=" + key;

  args = process.argv;

  next = false;

  feeling = "";

  args.forEach(function(val) {
    if (next === false) {
      if (val.indexOf("gifd") >= 0) {
        return next = true;
      }
    } else {
      return feeling = val;
    }
  });

  fetchGif = function(callback) {
    return http.get(url, function(res) {
      var str;
      res.setEncoding('utf8');
      str = "";
      res.on('data', function(chunk) {
        return str += chunk;
      });
      return res.on('end', function() {
        var img, json;
        json = JSON.parse(str);
        img = json.gif.gif;
        return copy(img, function() {
          return asciimo.write("Copied!", "banner3", function(art) {
            console.log("\n" + art.green);
            if (callback) {
              return callback();
            }
          });
        });
      });
    });
  };

  asciimo.write("gifD", "isometric2", function(art) {
    var feelings, rl;
    console.log(art.green);
    if (feeling === "") {
      rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout
      });
      feelings = ["happy", "sad", "excited", "angry", "lazy", "confused", "bored", "interested"];
      feeling = feelings[Math.floor(Math.random() * feelings.length)];
      return rl.question("What are you feeling? eg. " + feeling + " ", function(a) {
        if (!a) {
          a = feeling;
        }
        url = "" + url + "&term=" + a;
        return fetchGif(function() {
          return rl.close();
        });
      });
    } else {
      url = "" + url + "&term=" + feeling;
      return fetchGif();
    }
  });

}).call(this);
