// Generated by CoffeeScript 1.7.1
(function() {
  var asciimo, colors, copypaste, feeling, feelings, http, key, readline, rl, url;

  readline = require('readline');

  http = require('http');

  asciimo = require('./node_modules/asciimo/lib/asciimo').Figlet;

  colors = require('./node_modules/asciimo/lib/colors');

  copypaste = require('copy-paste');

  key = "dc6zaTOxFJmzC";

  url = "http://api.giphy.com/v1/gifs/random?api_key=" + key;

  rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });

  feelings = ["happy", "sad", "excited", "angry", "lazy", "confused", "bored", "interested"];

  feeling = feelings[Math.floor(Math.random() * feelings.length)];

  asciimo.write("gifME", "isometric2", function(art) {
    console.log(art.green);
    return rl.question("What are you feeling? eg. " + feeling + " ", function(a) {
      if (!a) {
        a = feeling;
      }
      url = "" + url + "&tag=" + a;
      return http.get(url, function(res) {
        var str;
        res.setEncoding('utf8');
        str = "";
        res.on('data', function(chunk) {
          return str += chunk;
        });
        return res.on('end', function() {
          var img, json;
          json = JSON.parse(str);
          img = json.data.image_original_url;
          return copy(img, function() {
            return asciimo.write("Copied!", "banner3", function(art) {
              console.log("\n" + art.green);
              return rl.close();
            });
          });
        });
      });
    });
  });

}).call(this);
